version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(levelname)s - p%(process)d/t%(thread)d - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

loggers:
  uvicorn:
    error:
      propagate: true
  # sciety_labs:
  #   # level: WARNING
  #   level: INFO
  # opensearch:
  #   level: WARNING
  # opensearchpy:
  #   level: WARNING

root:
  # level: WARNING
  level: INFO
  handlers: [console]
  propagate: no
